### ISSUE TITLE
rsxSetTransferImage doesn't work as expected

### ISSUE THREAD

**Issue by crystalct** [ps3dev/PSL1GHT#122]
`srcX` and `srcY` are ignored (always 0 and 0).
You have to add manually `(srcX + srcY * width_src_image) * bytes_per_pixel` to `srcOffset`

**Comment by shagkur** [comment]
I've just commited a fix for this. Can you give it a try.

**Comment by crystalct** [comment]
At home i will test it.

**Comment by crystalct** [comment]
Works! 

Do you have or know a place where find examples about RSX and freetypes fonts (not tiny3d) to use unicode fonts  (to use also japan characters) ?
