### ISSUE TITLE
How to compile the examples from the network/ folder? (ppu.mk is missing)

### ISSUE THREAD

**Issue by luizfernandonb** [ps3dev/PSL1GHT#124]
I was trying to compile some examples and when I'm going to compile the examples from the `network/` folder, the Makefile includes a file called `ppu.mk` that comes from the `$(PSL1GHT)/host` folder, but it's not there, I've already recompiled the toolchain from zero twice and the SDK too, but this folder is never created

[This line](https://github.com/ps3dev/PSL1GHT/blob/master/samples/network/networktest/Makefile#L6) includes the file I'm talking about

How to solve this?

**Comment by zeldin** [comment]
It looks like two of the examples there never were converted to the new layout.  Do they work if you just change the line to instead say `include $(PSL1GHT)/ppu_rules` like in the other network examples?

**Comment by luizfernandonb** [comment]
> It looks like two of the examples there never were converted to the new layout. Do they work if you just change the line to instead say `include $(PSL1GHT)/ppu_rules` like in the other network examples?

Unfortunately not
```
main.c
/mnt/e/Programacao/SDKs/PSL1GHT/samples/network/networktest/source/main.c:5:10: fatal error: psl1ght/lv2/net.h: No such file or directory
 #include <psl1ght/lv2/net.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [/mnt/e/Programacao/SDKs/PSL1GHT/build/base_rules:69: main.o] Error 1
make: *** [Makefile:58: build] Error 2
```

The `net.h` file does not exist in the `lv2/` folder

**Comment by zeldin** [comment]
Ok, looks like the C code needs updating too.  This include should be `#include <net/net.h>` now.

**Comment by zeldin** [comment]
Actually, #114 contains all the needed fixes AFAICT.
