### ISSUE TITLE
add access()

### ISSUE THREAD

**Issue by kazzmir** [ps3dev/PSL1GHT#36]
I would like to use the access() function, can it be added?

NAME
       access - check real user's permissions for a file

SYNOPSIS
       #include <unistd.h>

```
   int access(const char *pathname, int mode);
```

**Comment by bucanero** [comment]
An emulated implementation of `access()` was added to newlib >>  https://github.com/ps3dev/ps3toolchain/commit/3ab93e874652a0da04a5b2530fa837b1a0b41df7
