### ISSUE TITLE
internal narrowing conversion error in ppu/include/vectormath/cpp/quat_aos.h

### ISSUE THREAD

**Issue by ParzivalWolfram** [ps3dev/PSL1GHT#70]
Potential issue with PSL1GHT:

Reproduction code: `make -f Makefile.ps3` from https://github.com/emukidid/wii64-ps3 current master (commit 85b23eeaf0c3ef224cdde6074bcda99339b6274f for future reference)

Error: 
```
/usr/local/ps3dev/ppu/include/vectormath/cpp/quat_aos.h:502:100: error: narrowing conversion of '2147483648' from 'unsigned int' to 'int' inside { } [-Wnarrowing]
     return Quat( vec_xor( quat.get128(), ((vec_float4)(vec_int4){0x80000000,0x80000000,0x80000000,0}) ) );```

**Comment by miigotu** [comment]
You can add -Wno-narrowing to the cpp flags in that makefile.

It should work fine, but we should also explicitly  static_cast that line or update the include.

**Comment by zeldin** [comment]
Is the value supposed to be 2147483648?  In that case I guess the code should simply say
`(vec_uint4){0x80000000U,0x80000000U,0x80000000U,0}`
instead?

**Comment by ParzivalWolfram** [comment]
I'm unsure, but from the surrounding code, it seems 0x7FFFFFFF would be
sufficient. I'm not the greatest at C, however, so take someone else's word
for it, not mine.

**Comment by zeldin** [comment]
Since the value is an operand to XOR, using 0x7FFFFFFF would give a very different result I think.  The intention seems to be to invert the sign bit, not every bit _except_ the sign bit.  :smile_cat:

**Comment by zeldin** [comment]
Come to think of it, maybe the whole thing can be rewritten to
`     return Quat( vec_xor( quat.get128(), ((vec_float4){-0.0, -0.0, -0.0, 0.0})));`
without involving any integers at all?

**Comment by ParzivalWolfram** [comment]
I didn't catch that that was the intent, like I said, i'm not great at C...
hence the disclaimer.

**Comment by miigotu** [comment]
Pretty sure just changing the cast to vec_uint4 is enough:

```cpp
return Quat( vec_xor( quat.get128(), ((vec_float4)(vec_uint4){0x80000000,0x80000000,0x80000000,0}) ) );``
```

I don't have the toolchain/libraries set up to test that out though

**Comment by bucanero** [comment]
I've got a similar problem trying to build the `rsxtest` sample from PSL1GHT ( https://github.com/ps3dev/PSL1GHT/tree/master/samples/graphics/rsxtest )

by running `make`, I get the same error about the narrowing conversion.

Following @miigotu comment, I tried casting to `vec_uint4` (modified line 502 in `/usr/local/ps3dev/ppu/include/vectormath/cpp/quat_aos.h` )

Tried to compile again, and to my surprise, I've got a very weird error (at least for my limited knowledge):
```
% make
main.cpp
/Users/dparrino/github/psl1ght-libs/samples/psl1ght/graphics/rsxtest/source/main.cpp: In function 'int main(int, const char**)':
/Users/dparrino/github/psl1ght-libs/samples/psl1ght/graphics/rsxtest/source/main.cpp:556:6: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
  s32 ret,i;
      ^~~
/Users/dparrino/github/psl1ght-libs/samples/psl1ght/graphics/rsxtest/source/main.cpp: In function 'void program_exit_callback()':
/Users/dparrino/github/psl1ght-libs/samples/psl1ght/graphics/rsxtest/source/main.cpp:410:1: internal compiler error: in rs6000_savres_routine_name, at config/rs6000/rs6000.c:28661
 }
 ^
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[1]: *** [main.o] Error 1
make: *** [build] Error 2
```

did I truly broke gcc, or I did something wrong on my side?

thanks for the help

**Comment by miigotu** [comment]
@bucanero the first error is easily worked around, by passing `-Wno-unused-but-set-variable`

**Comment by bucanero** [comment]
> @bucanero the first error is easily worked around, by passing `-Wno-unused-but-set-variable` as a cflag.

oh yes, the unused variable is not a big deal, what I have no clue about is the `internal compiler error` ❓ 

```
/Users/dparrino/github/psl1ght-libs/samples/psl1ght/graphics/rsxtest/source/main.cpp:410:1: internal compiler error: in rs6000_savres_routine_name, at config/rs6000/rs6000.c:28661
 }
 ^
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
```

it's the first time I see gcc telling me to report a full bug report . I just wanted to check if it was a problem on my side , or someone else also got this issue when trying to build `rsxtest`

**Comment by miigotu** [comment]
Ideally someone should just update vectormath in PSL1GHT

**Comment by miigotu** [comment]
@bucanero can you try checking out the :bug/issue-70 branch and compile that?

**Comment by bucanero** [comment]
@miigotu sure, I'll check out and try to compile. 👍 

I'll report back with my results.

**Comment by bucanero** [comment]
Sorry for the delay, using the fix from `bug/issue-70` removed the narrowing conversion error, but the example still fails to compile.

I'll try #77 next.
