### ISSUE TITLE
-Os ( Optimize for space rather than speed) as CFLAGS makes Segmentation fault in compilation

### ISSUE THREAD

**Issue by crystalct** [ps3dev/PSL1GHT#78]
/home/crystal/tiny3D_ps3soundlib/PSL1GHT.samples/graphics/rsxtest/source/main.cpp:410:1: internal compiler error: in rs6000_savres_routine_name, at config/rs6000/rs6000.c:28661
 }
 ^

/home/crystal/tiny3D_ps3soundlib/PSL1GHT.samples/graphics/rsxtest/source/main.cpp:410:1: internal compiler error: Segmentation fault

**Comment by miigotu** [comment]
What if you change it to -std=c++14?

**Comment by crystalct** [comment]
That also happens  with .c sources.

**Comment by miigotu** [comment]
@crystalct because g++ is used for both c and c++.

**Comment by crystalct** [comment]
Ok,.... i try it

**Comment by crystalct** [comment]
No....
$ ppu-gcc main.c -O2 -Wall -mcpu=cell -I$PSL1GHT/ppu/include -I$PS3DEV/portlibs/ppu/include -I../include -c

crystal@DESKTOP-2FII39V ~/tiny3D_ps3soundlib/PSL1GHT.samples/graphics/cairo/source
$ ppu-gcc main.c -Os -std=c++14 -Wall -mcpu=cell -I$PSL1GHT/ppu/include -I$PS3DEV/portlibs/ppu/include -I../include -c
cc1: warning: command line option '-std=c++14' is valid for C++/ObjC++ but not for C
main.c: In function 'drawFrame':
main.c:101:1: internal compiler error: in rs6000_savres_routine_name, at config/rs6000/rs6000.c:28661
 }
 ^

main.c:101:1: internal compiler error: Segmentation fault
mmap: No such device
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.

crystal@DESKTOP-2FII39V ~/tiny3D_ps3soundlib/PSL1GHT.samples/graphics/cairo/source
$ ppu-g++ main.c -Os -std=c++14 -Wall -mcpu=cell -I$PSL1GHT/ppu/include -I$PS3DEV/portlibs/ppu/include -I../include -c
main.c: In function 'void drawFrame(rsxBuffer*, int)':
main.c:56:35: error: 'M_PI' was not declared in this scope
         cairo_rotate (cr, frame * M_PI / 180);
                                   ^~~~
main.c:56:35: note: suggested alternative: '__P'
         cairo_rotate (cr, frame * M_PI / 180);
                                   ^~~~
                                   __P
main.c:90:9: error: 'snprintf' was not declared in this scope
         snprintf (buf, 100, "FPS : %f", fps);
         ^~~~~~~~
main.c:90:9: note: suggested alternative: 'sprintf'
         snprintf (buf, 100, "FPS : %f", fps);
         ^~~~~~~~
         sprintf

crystal@DESKTOP-2FII39V ~/tiny3D_ps3soundlib/PSL1GHT.samples/graphics/cairo/source
$ ppu-gcc main.c -O2 -Wall -mcpu=cell -I$PSL1GHT/ppu/include -I$PS3DEV/portlibs/ppu/include -I../include -c

crystal@DESKTOP-2FII39V ~/tiny3D_ps3soundlib/PSL1GHT.samples/graphics/cairo/source
$

**Comment by miigotu** [comment]
![info](https://user-images.githubusercontent.com/390379/84824333-bfe83e80-afed-11ea-9bef-58c36333334e.png)

**Comment by miigotu** [comment]
Either way, its just a sample so I removed the -Os and it will be fine.
