### ISSUE TITLE
psl1ght docs

### ISSUE THREAD

**Issue by bucanero** [ps3dev/PSL1GHT#79]
Hello,

Not a real issue, but I wanted to discuss if you'd like to add the doxygen-generated PSL1GHT docs to the repo.

I've added them in my fork (https://github.com/bucanero/PSL1GHT/tree/master/docs), and even if they might be outdated, I still think it's good to share them with any user of the sdk.

So if you want, I can submit a PR with the `/docs` folder to be added.

cheers

**Comment by miigotu** [comment]
I will never say no to tests or documentation. Please do. I don't have access to the repo settings or we could also set up a GitHub pages for it and some automated PR builds and tests. For example I use GitHub workflows on sickchill to automatically test and then build a docker image and release it on every push.

**Comment by bucanero** [comment]
great!, I've just submitted the docs I generated in a new PR.
too bad we can't add some workflows, that would be neat 😄

**Comment by miigotu** [comment]
Apparently we can use workflows. Working on setting up autobuild of ps3toolchain (with buildx manifest so it works cross platform) and then using that container to build PSL1GHT in a PSL1GHT workflow, and then an autobuild of a docker container that is FROM ps3toolchain and adds PSL1GHT and ps3libraries.

**Comment by bucanero** [comment]
amazing news! 😄  
I wish I could help on that, but I'm quite new on the docker stuff and workflows

the only thing I can share is a simple workflow I made on my fork, that builds the whole toolchain (toolchain+psl1ght+ps3libraries) for mac and linux:
https://github.com/bucanero/ps3toolchain/blob/master/.github/workflows/build.yml

I'll keep an eye on your updates so I can learn a bit
cheers

**Comment by miigotu** [comment]
Nice, Im actually going to use some of that workflow you made.
