### ISSUE TITLE
struct sockaddr_storage definition missing in net/socket.h, causing "incomplete type is not allowed"

### ISSUE THREAD

**Issue by dee12452** [ps3dev/PSL1GHT#95]
Hello,

Trying to port over a lib for a project I picked up and I'm running into an issue where psl1ght doesn't have an implementation for sockaddr_storage in any of the socket.h. 

Looking at this doc on sys/socket.h
https://pubs.opengroup.org/onlinepubs/009696799/basedefs/sys/socket.h.html

Looks like 
```
The <sys/socket.h> header shall define the sockaddr_storage structure. This structure shall be:

Large enough to accommodate all supported protocol-specific address structures

Aligned at an appropriate boundary so that pointers to it can be cast as pointers to protocol-specific address structures and used to access the fields of those structures without alignment problems

The sockaddr_storage structure shall contain at least the following members:

sa_family_t   ss_family
```

Just wondering why it doesn't exist? Is it because the PS3 doesn't handle IPV6? 

I'm not familiar with networking code so I figured I'd ask more knowledgable people before I just hack my own definition into my fork of psl1ght and truck on. 

Thanks!

**Comment by dee12452** [comment]
Seems related to the question / request here
https://github.com/ps3dev/ps3toolchain/issues/78
Where we are just missing support for IPV6 headers and structs

**Comment by miigotu** [comment]
Have you done the check suggested in https://github.com/ps3dev/ps3toolchain/issues/78#issuecomment-408960706 ?
If it is just missing from the header you are welcome to make a PR to add the code. But first check that it is even going to work 

___check that the SPRX actually supports IPv6 though (i.e. that socket(PF_INET6, SOCK_DGRAM, 0) doesn't just return an error)___

**Comment by dee12452** [comment]
Not quite, was going to do as suggested there though. I'll go ahead and close this issue and just use the other to track the work
